import Vue from 'vue'
import '@/util/css/global.css'
import { Button, Slider, Carousel, CarouselItem, Input, Row, Col, Tag, Table, TableColumn, Card, Scrollbar, Drawer, Menu, MenuItem, Divider, Pagination, Image, Skeleton, SkeletonItem, Loading, InfiniteScroll } from 'element-ui'
Vue.use(Button)
Vue.use(Slider)
Vue.use(Carousel)
Vue.use(CarouselItem)
Vue.use(Input)
Vue.use(Row)
Vue.use(Col)
Vue.use(Tag)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Card)
Vue.use(Scrollbar)
Vue.use(Drawer)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(Divider)
Vue.use(Pagination)
Vue.use(Image)
Vue.use(Skeleton)
Vue.use(SkeletonItem)
Vue.use(InfiniteScroll)
Vue.use(Loading.directive);